### ISSUE TITLE
Resetting Aquara Motion Sensors integrated through zigbee2mqtt

### ISSUE THREAD

**Issue by dvbit** [wernerhp/appdaemon_aqara_motion_sensors#3]
As per the title I have dismissed the homeassistant xiaomi platform in favour of zigbee2mqtt.
Not really an issue but rather a request for improvment.
I read the code and I see it is based on that component.
My question / request is : would it be possible to extend the automation also to aquara through 2zmqtt ?
TX

**Comment by htvekov** [comment]
Hi' @dvbit 

Using z2m integration for hw hacked Xiaomi pir sensors, you can define `occupancy_timeout` in share/zigbee2mqtt/devices.yaml 
This resets HA sensor state after defined time period.

```yaml
'0x00158d00031b0e12':
  friendly_name: Hallway
  occupancy_timeout: 8
```

Ciao !
